// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/chatroom/internal/biz"
	"github.com/murphy-hc/h-im/services/chatroom/internal/conf"
	"github.com/murphy-hc/h-im/services/chatroom/internal/data"
	"github.com/murphy-hc/h-im/services/chatroom/internal/server"
	"github.com/murphy-hc/h-im/services/chatroom/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	chatroomRepo := data.NewChatroomRepo(dataData)
	chatroomUseCase := biz.NewChatroomUseCase(chatroomRepo)
	chatroomService := service.NewChatroomService(chatroomUseCase)
	grpcServer := server.NewGRPCServer(confServer, chatroomService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
