// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/murphy-hc/h-im/services/group/internal/biz"
	"github.com/murphy-hc/h-im/services/group/internal/conf"
	"github.com/murphy-hc/h-im/services/group/internal/data"
	"github.com/murphy-hc/h-im/services/group/internal/server"
	"github.com/murphy-hc/h-im/services/group/internal/service"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, meter metric.Meter) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bc)
	if err != nil {
		return nil, nil, err
	}
	groupRepo := data.NewGroupRepo(dataData)
	groupUseCase := biz.NewGroupUseCase(groupRepo)
	groupService := service.NewGroupService(groupUseCase)
	grpcServer := server.NewGRPCServer(bc, meter, groupService)
	httpServer := server.NewHTTPServer(bc, meter)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
