// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/group/internal/biz"
	"github.com/murphy-hc/h-im/services/group/internal/conf"
	"github.com/murphy-hc/h-im/services/group/internal/data"
	"github.com/murphy-hc/h-im/services/group/internal/server"
	"github.com/murphy-hc/h-im/services/group/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	groupRepo := data.NewGroupRepo(dataData)
	groupUseCase := biz.NewGroupUseCase(groupRepo)
	groupService := service.NewGroupService(groupUseCase)
	grpcServer := server.NewGRPCServer(confServer, groupService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
