apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: default
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9101
      targetPort: 9101
    - name: http
      port: 8101
      targetPort: 8101
  selector:
    app: user
