apiVersion: v1
kind: Service
metadata:
  name: gateway-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: gateway
  ports:
    - name: grpc
      port: 9200
      targetPort: 9200
