// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/user/internal/biz"
	"github.com/murphy-hc/h-im/services/user/internal/conf"
	"github.com/murphy-hc/h-im/services/user/internal/data"
	"github.com/murphy-hc/h-im/services/user/internal/server"
	"github.com/murphy-hc/h-im/services/user/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, userService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
