// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/push/internal/biz"
	"github.com/murphy-hc/h-im/services/push/internal/conf"
	"github.com/murphy-hc/h-im/services/push/internal/data"
	"github.com/murphy-hc/h-im/services/push/internal/server"
	"github.com/murphy-hc/h-im/services/push/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	pushRepo := data.NewPushRepo(dataData)
	pushUseCase := biz.NewPushUseCase(pushRepo)
	pushService := service.NewPushService(pushUseCase)
	grpcServer := server.NewGRPCServer(confServer, pushService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
