// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/murphy-hc/h-im/services/push/internal/biz"
	"github.com/murphy-hc/h-im/services/push/internal/conf"
	"github.com/murphy-hc/h-im/services/push/internal/data"
	"github.com/murphy-hc/h-im/services/push/internal/server"
	"github.com/murphy-hc/h-im/services/push/internal/service"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, meter metric.Meter) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bc)
	if err != nil {
		return nil, nil, err
	}
	pushRepo := data.NewPushRepo(dataData)
	pusher := data.NewPusher()
	pushUseCase := biz.NewPushUseCase(pushRepo, pusher)
	pushService := service.NewPushService(pushUseCase)
	grpcServer := server.NewGRPCServer(bc, meter, pushService)
	httpServer := server.NewHTTPServer(bc, meter)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
