server:
  env: "dev"
  http:
    network: "tcp"
    addr: ":8105"
  grpc:
    network: "tcp"
    addr: ":9105"

otel:
  service_name: "him-chatroom"
  endpoint: "localhost:4318"
  sample_rate: 1.0
  path: "/v1/traces"
  timeout: "5s"
  insecure: true
  transport: "http"

log:
  level: "info"

data:
  database:
    chatroom:
      dsn: "postgres://him:him_secret@localhost:5432/him?sslmode=disable"
      max_idle_conns: 10
      max_open_conns: 50
  redis:
    network: "tcp"
    addr: "localhost:6379"
    password: ""
    read_timeout: "1s"
    write_timeout: "1s"
