apiVersion: v1
kind: Service
metadata:
  name: chatroom
  namespace: default
  labels:
    app: chatroom
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9105
      targetPort: 9105
    - name: http
      port: 8105
      targetPort: 8105
  selector:
    app: chatroom
