// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/murphy-hc/h-im/services/gateway/internal/biz"
	"github.com/murphy-hc/h-im/services/gateway/internal/conf"
	"github.com/murphy-hc/h-im/services/gateway/internal/server"
	"github.com/murphy-hc/h-im/services/gateway/internal/service"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, meter metric.Meter) (*kratos.App, func(), error) {
	confServer := bc.Server
	gatewayUseCase := biz.NewGatewayUseCase()
	gatewayService := service.NewGatewayService(gatewayUseCase)
	wsServer := server.NewWSServer(confServer, gatewayService)
	httpServer := server.NewHTTPServer(bc, meter)
	connManager := biz.NewConnManager()
	gatewayGrpcService := service.NewGatewayGrpcService(connManager)
	grpcServer := server.NewGRPCServer(bc, meter, gatewayGrpcService)
	app := newApp(wsServer, httpServer, grpcServer)
	return app, func() {
	}, nil
}
