// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/murphy-hc/h-im/services/gateway/internal/biz"
	"github.com/murphy-hc/h-im/services/gateway/internal/conf"
	"github.com/murphy-hc/h-im/services/gateway/internal/data"
	"github.com/murphy-hc/h-im/services/gateway/internal/server"
	"github.com/murphy-hc/h-im/services/gateway/internal/service"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, meter metric.Meter) (*kratos.App, func(), error) {
	confServer := bc.Server
	server_WS := confServer.Ws
	upgrader := server.NewUpgrader(server_WS)
	client, cleanup, err := data.NewRedisClient(bc)
	if err != nil {
		return nil, nil, err
	}
	connManager := data.NewConnManager(client)
	messageClient, cleanup2, err := data.NewMessageClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userStatusClient, cleanup3, err := data.NewUserStatusClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	heartbeatConfig := biz.NewHeartbeatConfig(bc)
	string2 := data.GatewayAddr()
	gatewayUseCase := biz.NewGatewayUseCase(connManager, messageClient, userStatusClient, heartbeatConfig, string2)
	user := bc.User
	dataData, cleanup4, err := data.NewData(bc)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appRepo := data.NewAppRepo(dataData)
	gatewayService := service.NewGatewayService(gatewayUseCase, connManager, upgrader, user, appRepo)
	wsServer := server.NewWSServer(confServer, upgrader, gatewayService)
	httpServer := server.NewHTTPServer(bc, meter)
	gatewayGrpcService := service.NewGatewayGrpcService(connManager)
	grpcServer := server.NewGRPCServer(bc, meter, gatewayGrpcService)
	app := newApp(wsServer, httpServer, grpcServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
