apiVersion: v1
kind: Service
metadata:
  name: sequence
  namespace: default
  labels:
    app: sequence
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9108
      targetPort: 9108
    - name: http
      port: 8108
      targetPort: 8108
  selector:
    app: sequence
