// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/message/internal/biz"
	"github.com/murphy-hc/h-im/services/message/internal/conf"
	"github.com/murphy-hc/h-im/services/message/internal/data"
	"github.com/murphy-hc/h-im/services/message/internal/server"
	"github.com/murphy-hc/h-im/services/message/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	messageRepo := data.NewMessageRepo(dataData)
	messageUseCase := biz.NewMessageUseCase(messageRepo)
	messageService := service.NewMessageService(messageUseCase)
	grpcServer := server.NewGRPCServer(confServer, messageService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
