// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: services/gateway/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Log           *Log                   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Otel          *Otel                  `protobuf:"bytes,4,opt,name=otel,proto3" json:"otel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetOtel() *Otel {
	if x != nil {
		return x.Otel
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	Ws            *Server_WS             `protobuf:"bytes,2,opt,name=ws,proto3" json:"ws,omitempty"`
	Http          *Server_HTTP           `protobuf:"bytes,3,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Server) GetWs() *Server_WS {
	if x != nil {
		return x.Ws
	}
	return nil
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Otel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	SampleRate    float64                `protobuf:"fixed64,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Insecure      bool                   `protobuf:"varint,6,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Transport     string                 `protobuf:"bytes,7,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Otel) Reset() {
	*x = Otel{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Otel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Otel) ProtoMessage() {}

func (x *Otel) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Otel.ProtoReflect.Descriptor instead.
func (*Otel) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Otel) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Otel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Otel) GetSampleRate() float64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Otel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Otel) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Otel) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Otel) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type Server_WS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_WS) Reset() {
	*x = Server_WS{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_WS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_WS) ProtoMessage() {}

func (x *Server_WS) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_WS.ProtoReflect.Descriptor instead.
func (*Server_WS) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_WS) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_WS) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_services_gateway_internal_conf_conf_proto protoreflect.FileDescriptor

const file_services_gateway_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	")services/gateway/internal/conf/conf.proto\x12\x10him.gateway.conf\x1a\x1egoogle/protobuf/duration.proto\"\x92\x01\n" +
	"\tBootstrap\x120\n" +
	"\x06server\x18\x01 \x01(\v2\x18.him.gateway.conf.ServerR\x06server\x12'\n" +
	"\x03log\x18\x03 \x01(\v2\x15.him.gateway.conf.LogR\x03log\x12*\n" +
	"\x04otel\x18\x04 \x01(\v2\x16.him.gateway.conf.OtelR\x04otel\"\x99\x02\n" +
	"\x06Server\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12+\n" +
	"\x02ws\x18\x02 \x01(\v2\x1b.him.gateway.conf.Server.WSR\x02ws\x121\n" +
	"\x04http\x18\x03 \x01(\v2\x1d.him.gateway.conf.Server.HTTPR\x04http\x1a2\n" +
	"\x02WS\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x1b\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\"\xe9\x01\n" +
	"\x04Otel\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x01R\n" +
	"sampleRate\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1a\n" +
	"\binsecure\x18\x06 \x01(\bR\binsecure\x12\x1c\n" +
	"\ttransport\x18\a \x01(\tR\ttransportB?Z=github.com/murphy-hc/h-im/services/gateway/internal/conf;confb\x06proto3"

var (
	file_services_gateway_internal_conf_conf_proto_rawDescOnce sync.Once
	file_services_gateway_internal_conf_conf_proto_rawDescData []byte
)

func file_services_gateway_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_services_gateway_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_services_gateway_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_gateway_internal_conf_conf_proto_rawDesc), len(file_services_gateway_internal_conf_conf_proto_rawDesc)))
	})
	return file_services_gateway_internal_conf_conf_proto_rawDescData
}

var file_services_gateway_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_gateway_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: him.gateway.conf.Bootstrap
	(*Server)(nil),              // 1: him.gateway.conf.Server
	(*Log)(nil),                 // 2: him.gateway.conf.Log
	(*Otel)(nil),                // 3: him.gateway.conf.Otel
	(*Server_WS)(nil),           // 4: him.gateway.conf.Server.WS
	(*Server_HTTP)(nil),         // 5: him.gateway.conf.Server.HTTP
	(*durationpb.Duration)(nil), // 6: google.protobuf.Duration
}
var file_services_gateway_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: him.gateway.conf.Bootstrap.server:type_name -> him.gateway.conf.Server
	2, // 1: him.gateway.conf.Bootstrap.log:type_name -> him.gateway.conf.Log
	3, // 2: him.gateway.conf.Bootstrap.otel:type_name -> him.gateway.conf.Otel
	4, // 3: him.gateway.conf.Server.ws:type_name -> him.gateway.conf.Server.WS
	5, // 4: him.gateway.conf.Server.http:type_name -> him.gateway.conf.Server.HTTP
	6, // 5: him.gateway.conf.Otel.timeout:type_name -> google.protobuf.Duration
	6, // 6: him.gateway.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_services_gateway_internal_conf_conf_proto_init() }
func file_services_gateway_internal_conf_conf_proto_init() {
	if File_services_gateway_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_gateway_internal_conf_conf_proto_rawDesc), len(file_services_gateway_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_gateway_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_services_gateway_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_services_gateway_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_services_gateway_internal_conf_conf_proto = out.File
	file_services_gateway_internal_conf_conf_proto_goTypes = nil
	file_services_gateway_internal_conf_conf_proto_depIdxs = nil
}
