// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/murphy-hc/h-im/services/media/internal/biz"
	"github.com/murphy-hc/h-im/services/media/internal/conf"
	"github.com/murphy-hc/h-im/services/media/internal/data"
	"github.com/murphy-hc/h-im/services/media/internal/server"
	"github.com/murphy-hc/h-im/services/media/internal/service"
	"go.opentelemetry.io/otel/metric"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, meter metric.Meter) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData)
	mediaUseCase := biz.NewMediaUseCase(mediaRepo)
	mediaService := service.NewMediaService(mediaUseCase)
	grpcServer := server.NewGRPCServer(bc, meter, mediaService)
	httpServer := server.NewHTTPServer(bc, meter)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
