// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/auth/internal/biz"
	"github.com/murphy-hc/h-im/services/auth/internal/conf"
	"github.com/murphy-hc/h-im/services/auth/internal/data"
	"github.com/murphy-hc/h-im/services/auth/internal/server"
	"github.com/murphy-hc/h-im/services/auth/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData)
	authUseCase := biz.NewAuthUseCase(authRepo)
	authService := service.NewAuthService(authUseCase)
	grpcServer := server.NewGRPCServer(confServer, authService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
