apiVersion: v1
kind: Service
metadata:
  name: push
  namespace: default
  labels:
    app: push
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9106
      targetPort: 9106
    - name: http
      port: 8106
      targetPort: 8106
  selector:
    app: push
