// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/sequence/internal/biz"
	"github.com/murphy-hc/h-im/services/sequence/internal/conf"
	"github.com/murphy-hc/h-im/services/sequence/internal/server"
	"github.com/murphy-hc/h-im/services/sequence/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data *conf.Data) (*grpc.Server, func(), error) {
	sequenceUseCase := biz.NewSequenceUseCase()
	sequenceService := service.NewSequenceService(sequenceUseCase)
	grpcServer := server.NewGRPCServer(confServer, sequenceService)
	return grpcServer, func() {
	}, nil
}
