// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/murphy-hc/h-im/services/contact/internal/biz"
	"github.com/murphy-hc/h-im/services/contact/internal/conf"
	"github.com/murphy-hc/h-im/services/contact/internal/data"
	"github.com/murphy-hc/h-im/services/contact/internal/server"
	"github.com/murphy-hc/h-im/services/contact/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data) (*grpc.Server, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	contactRepo := data.NewContactRepo(dataData)
	contactUseCase := biz.NewContactUseCase(contactRepo)
	contactService := service.NewContactService(contactUseCase)
	grpcServer := server.NewGRPCServer(confServer, contactService)
	return grpcServer, func() {
		cleanup()
	}, nil
}
