apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: default
  labels:
    app: message
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9102
      targetPort: 9102
    - name: http
      port: 8102
      targetPort: 8102
  selector:
    app: message
