server:
  grpc:
    addr: ":9108"

data:
  database:
    driver: postgres
    source: postgres://him:him_secret@localhost:5432/him?sslmode=disable
  redis:
    addr: localhost:6379
    password: ""
    db: 0
