apiVersion: v1
kind: Service
metadata:
  name: group
  namespace: default
  labels:
    app: group
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9104
      targetPort: 9104
    - name: http
      port: 8104
      targetPort: 8104
  selector:
    app: group
