server:
  env: "dev"
  http:
    network: "tcp"
    addr: ":8101"
  grpc:
    network: "tcp"
    addr: ":9101"

otel:
  service_name: "him-user"
  endpoint: "localhost:4318"
  sample_rate: 0.1
  path: "/v1/traces"
  timeout: "5s"
  insecure: true
  transport: "http"

log:
  level: "info"

data:
  database:
    user:
      dsn: "him:him_secret@tcp(localhost:3306)/him?charset=utf8mb4&parseTime=True"
      max_idle_conns: 10
      max_open_conns: 50
  redis:
    network: "tcp"
    addr: "localhost:6379"
    password: ""
    read_timeout: "1s"
    write_timeout: "1s"
