server:
  env: "dev"
  http:
    network: "tcp"
    addr: ":8102"
  grpc:
    network: "tcp"
    addr: ":9102"

otel:
  service_name: "him-message"
  endpoint: "localhost:4318"
  sample_rate: 1.0
  path: "/v1/traces"
  timeout: "5s"
  insecure: true
  transport: "http"

log:
  level: "info"

data:
  database:
    message:
      dsn: "him:him_secret@tcp(localhost:3306)/him?charset=utf8mb4&parseTime=True""
      max_idle_conns: 10
      max_open_conns: 50
  redis:
    network: "tcp"
    addr: "localhost:6379"
    password: ""
    read_timeout: "1s"
    write_timeout: "1s"
  kafka:
    brokers:
      - "localhost:9092"
    group_id: "message-service"
    topic: "him.private.message"
